#!/usr/bin/env bash
#install nginx and fix 'Hello World!' in file 

#update package list and install nginx with -yes respp
sudo apt-get update -y 
sudo apt-get install -y nginx
echo "server {
	listen 80 default_server;
    	listen [::]:80 default_server;

		location / {
		return 200 'Hello World!';
	}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
