#!/usr/bin/env bash
#this script configures web-02 to be identical to web-01

sudo apt-get update
sudo apt-get -y install nginx
echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/sites-available/default
sudo service nginx restart
