#!/usr/bin/env bash
#this script configures web-02 to be identical to web-01

sudo apt-get update
sudo apt-get -y install nginx
header="\tadd_header X-Served-By $HOSTNAME;\n"
sed -i "48i\\$header" /etc/sites-available/default
sudo service nginx restart
