#!/usr/bin/env bash
# this script displays contt of passwd
while IFS=: read -r username password _ groupid userinfo homedir commandshell
do
   echo "The user $username is part of the $groupid gang, lives in $homedir and rides $commandshell. $username's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
