#!/usr/bin/env bash
#start apache inside docker
mkdir my-apache-container
cd my-apache-container
mkdir html
echo "Hello Holberton" > html/index.html
# Use the official Apache image as the base image
FROM httpd:latest

# Copy the HTML file into the Apache document root
COPY ./html/index.html /usr/local/apache2/htdocs/index.html
docker build -t my-apache-container .
docker run -d -p 8080:80 my-apache-container
